# Generated by Django 2.1.7 on 2019-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
