# Generated by Django 2.1.2 on 2018-11-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181109_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.News'),
        ),
    ]
