# Generated by Django 2.1.2 on 2018-11-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='tag',
        ),
    ]
