# Generated by Django 2.1.2 on 2018-11-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181111_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='usage',
        ),
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Attachment'),
            preserve_default=False,
        ),
    ]
