# Generated by Django 2.1.2 on 2018-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181114_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='label',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('link', 'link'), ('file', 'file')], default='link', max_length=50),
        ),
    ]
