# Generated by Django 2.1.2 on 2018-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_attachment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
