# Generated by Django 2.1.3 on 2018-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181119_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_marked', to='api.Tag'),
        ),
    ]
