# Generated by Django 2.1.3 on 2018-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181127_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='api.Tag'),
        ),
    ]
