# Generated by Django 2.1.3 on 2018-12-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
