# Generated by Django 2.1.3 on 2019-01-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='news',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
